### PR TITLE
Change the default text of the sort button on the recent page

### PR DESCRIPTION
**Pull request by dominklenda**
Update in the  "minor esthetic/stylistic tweaks #96"

> Recent page: Update text from "SORT BY: NEWEST FIRST" simply to "SORT BY" (just like on search results page, e.g. https://curatescience.org/app/search/?q=disgust) 5 points

### CODE REVIEW

**Comment by eplebel** [comment]
hmm.... are you sure this is *ONLY* removing the ": NEWEST FIRST" text, rather than nullifying the actual SORT criteria of the recent articles??

from my understanding look at the SortButtong code, https://github.com/ScienceCommons/curate_science/blob/ccbe51599d17decf369d139f30cc5b13c1b96308/src/components/SortArticlesButton.jsx#L88 , all we'd need to do is remove the
`{ sorted_by ? <span>: { sorted_by }</span> : null }` after the "Sort by" (on line 88)

**Comment by dominklenda** [comment]
hmm i think it does the same thing as in the [SearchResults page](https://github.com/ScienceCommons/curate_science/blob/ccbe51599d17decf369d139f30cc5b13c1b96308/src/pages/SearchResults.jsx#L52): it sets **default**  "SORT BY"  and `null`, which gives just "SORT BY", which is replaced by other labels "SORT BY" and ": NEWEST FIRST" or "SORT BY" and ": IMPACT" when one of them is clicked.  

i assumed that we do not want to **completely** remove the second part (NEWEST or IMPACT) of the SORT BY label because a user can forget which criterion she/he used so she has to click it again to make sure.

or maybe not and we should simplify ui and remove the second part of the label completely as you showed, by removing. `{ sorted_by ? <span>: { sorted_by }</span> : null }`. then the SORT BY label would be changed on the SearchResults page as well. after writing this and doing some more testing i guess that we can remove it completely :sweat_smile:

so you decide, just let me know

**Comment by eplebel** [comment]
ah OK, i did misunderstand parts of that.  So yes your fix would be an improvement, but it would be better if you can update it so that even after an article list is sorted, it still only displays "SORT BY" (because on smaller screens, there's simply no horizontal room to display that much text), for Recent page and Search results page.  

Of course, the downside, as you mention, is that a user could forget the sort order, and must click on the Sort button to see the criterion, but that's still overall more optimal (though i guess a fancier/better solution would be to render different things based on the viewport size, but that's too much work given the priority level of this issue relative to all the other outstanding issues!)

**Comment by dominklenda** [comment]
ok, i see now, thanks. i'm ` { sorted_by ? <span>: { sorted_by }</span> : null }` this part.

**Comment by eplebel** [comment]
ok thanks, and this will update it on both the Recent page and Search results page correct?

**Comment by dominklenda** [comment]
yes, i rechecked it, it will update both, Recent and Search results pages

**Pull request merged**
